# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled68.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_WxbzapkmldnhB-jn_WqOM86OI4-Typa
"""

def unique_list(n):
  x = []
  for a in n:
    if a not in x:
      x.append(a)
  return x
 
print(unique_list([3,14,2,3,12,2,14,12,7,6,14]))