# -*- coding: utf-8 -*-
"""Copy of Untitled68.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10PTL9lN8dHSOuBC80OzTNB3xuQD3MNhz
"""

animal = ['Deer', 'Tiger', 'Fox', 'Donkey ', 'Lion', 'Monkey']
animal = [x for (i,x) in enumerate(animal) if i not in (0,4,5)]
print(animal)