# -*- coding: utf-8 -*-
"""Copy of Untitled68.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10PTL9lN8dHSOuBC80OzTNB3xuQD3MNhz
"""

def Cloning(li1): 
 
    li_copy = [] 
 
    li_copy.extend(li1) 
 
    return li_copy 
 
 
li1 = [5,3,10,30,12,11,5,4] 
 
li2 = Cloning(li1) 
 
print("Original List:", li1) 
 
print("After Cloning:", li2)