# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled68.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_WxbzapkmldnhB-jn_WqOM86OI4-Typa
"""

def up_low(s):      
    u = sum(1 for i in s if i.isupper())
    l = sum(1 for i in s if i.islower())
    print( "No. of Upper case characters : %s", u) 
    print ("No. of Lower case characters : %s", l) 
 
up_low("The GITAM UniVersity Is in BanGalore ")