# -*- coding: utf-8 -*-
"""Copy of Untitled68.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10PTL9lN8dHSOuBC80OzTNB3xuQD3MNhz
"""

num= [21,18,13,47,123,40,57,60]
num = [x for x in num if x%2!=0]
print(num)